//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOTHANG
    {
        public string MABAOCAOTHANG { get; set; }
        public string MABAOCAONGAY { get; set; }
        public string MALOAITK { get; set; }
        public System.DateTime NGAYBAOCAO { get; set; }
        public int THANG { get; set; }
        public int SOMO { get; set; }
        public int SODONG { get; set; }
        public double CHENHLECH { get; set; }
    
        public virtual BAOCAONGAY BAOCAONGAY { get; set; }
        public virtual LOAITIETKIEM LOAITIETKIEM { get; set; }
    }
}
