//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEURUTTIEN
    {
        public string MAPHIEURT { get; set; }
        public string MAKH { get; set; }
        public double SOTIENRUT { get; set; }
        public System.DateTime NGAYRUT { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
