//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanlySoTietKiemEntities : DbContext
    {
        public QuanlySoTietKiemEntities()
            : base("name=QuanlySoTietKiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAITIETKIEM> LOAITIETKIEMs { get; set; }
        public virtual DbSet<PHIEUGUITIEN> PHIEUGUITIENs { get; set; }
        public virtual DbSet<PHIEURUTTIEN> PHIEURUTTIENs { get; set; }
        public virtual DbSet<SOTIETKIEM> SOTIETKIEMs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
    }
}
