//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGUITIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUGUITIEN()
        {
            this.SOTIETKIEMs = new HashSet<SOTIETKIEM>();
        }
    
        public string MAPHIEUGT { get; set; }
        public string MAKH { get; set; }
        public double SOTIENGUI { get; set; }
        public System.DateTime NGAYGUI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTIETKIEM> SOTIETKIEMs { get; set; }
    }
}
